## Introduction to PyTorch

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.7.1+cpu


In [4]:
!nvidia-smi

Thu Jun 12 15:45:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GT 1030       WDDM  |   00000000:01:00.0  On |                  N/A |
| 30%   39C    P8             N/A /   30W |     706MiB /   2048MiB |     10%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Introduction to Tensors

### Creating Tensors

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [9]:
# Get tensir back as Python int
scalar.item()

7

In [12]:
# Vector: magnitude + direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([7, 8])

In [21]:
MATRIX[1]

tensor([ 9, 10])

In [22]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])